Resources:
  ConfigBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "musa-website-lambda-edge-test-bucket-081224v4"

  ConfigBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ConfigBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub "arn:aws:s3:::${ConfigBucket}/*"
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}"

  OriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Description: Allow CloudFront to access the bucket
        Name: AllowCloudFrontAccessToBucket
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
                - edgelambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: S3AccessPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource:
                  - !Sub "arn:aws:s3:::${ConfigBucket}/*"

        - PolicyName: CloudWatchLogsPolicy # Added policy for CloudWatch Logs
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "arn:aws:logs:*:*:*"

  ConfigUpdateLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-config-lambda"
      Runtime: nodejs20.x
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          'use strict';
            export.handler = (event, context, callback) => {

                //Get contents of response
                const response = event.Records[0].cf.response;
                const headers = response.headers;

                //Set new headers
                headers['strict-transport-security'] = [{key: 'Strict-Transport-Security', value: 'max-age= 63072000; includeSubdomains; preload'}];
                headers['content-security-policy'] = [{key: 'Content-Security-Policy', value: "default-src 'none'; img-src 'self'; script-src 'self'; style-src 'self'; object-src 'none'"}];
                headers['x-content-type-options'] = [{key: 'X-Content-Type-Options', value: 'nosniff'}];
                headers['x-frame-options'] = [{key: 'X-Frame-Options', value: 'DENY'}];
                headers['x-xss-protection'] = [{key: 'X-XSS-Protection', value: '1; mode=block'}];
                headers['referrer-policy'] = [{key: 'Referrer-Policy', value: 'same-origin'}];
                headers['x-teeeeeest-header'] = [{key: 'X-Teeeeeest-Header', value: 'teeeest-value'}];

                //Return modified response
                callback(null, response);
            };

  ConfigUpdateLambdaVersion:
    Type: AWS::Lambda::Version
    Properties:
      FunctionName: !Ref ConfigUpdateLambda

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: "musa-s3-lambda-edge-test-distribution"
        Enabled: true
        DefaultRootObject: "default-config.json"
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: true
          TargetOriginId: s3Origin
          ViewerProtocolPolicy: redirect-to-https
          LambdaFunctionAssociations:
            - EventType: origin-response
              LambdaFunctionARN: !Ref ConfigUpdateLambdaVersion
        Origins:
          - Id: s3Origin
            DomainName: !GetAtt ConfigBucket.DomainName
            OriginAccessControlId: !Ref OriginAccessControl
            S3OriginConfig: {}

Outputs:
  ConfigLambdaFunction:
    Description: "Config Lambda Function ARN"
    Value: !Ref ConfigUpdateLambdaVersion

  CloudFrontDistributionDomainName:
    Description: "CloudFront Distribution Domain Name"
    Value: !GetAtt CloudFrontDistribution.DomainName
